### 第1章 Opencv 入门

#### 1.1 环境配置

- miniconda 下载配置：https://www.anaconda.com/download/success

- 创建名为 myenv 的新环境（推荐指定 Python 版本）

```CLI
    conda create -n myenv python=3.xx
```
    Python 3.10: 2026-10 End of support
- 配置 OpenCV
```CLI
    pip install opencv-python
    pip install opencv-contrib-python
```

#### 1.2 图像处理的基本操作

In [3]:
import cv2
lena = cv2.imread("lena.bmp")
print(type(lena))
print(lena.shape)
print(lena) # 输出图像的像素值

<class 'numpy.ndarray'>
(256, 256, 3)
[[[162 162 162]
  [162 162 162]
  [160 160 160]
  ...
  [170 170 170]
  [171 171 171]
  [142 142 142]]

 [[162 162 162]
  [162 162 162]
  [160 160 160]
  ...
  [171 171 171]
  [173 173 173]
  [146 146 146]]

 [[163 163 163]
  [160 160 160]
  [160 160 160]
  ...
  [158 158 158]
  [149 149 149]
  [115 115 115]]

 ...

 [[ 50  50  50]
  [ 52  52  52]
  [ 52  52  52]
  ...
  [ 82  82  82]
  [ 92  92  92]
  [ 93  93  93]]

 [[ 45  45  45]
  [ 49  49  49]
  [ 50  50  50]
  ...
  [ 93  93  93]
  [101 101 101]
  [ 99  99  99]]

 [[ 45  45  45]
  [ 56  56  56]
  [ 51  51  51]
  ...
  [ 99  99  99]
  [103 103 103]
  [107 107 107]]]


In [5]:
if lena is not None:
	cv2.imshow("demo", lena) # 创建窗口demo，并显示图像
	cv2.waitKey(0)	# 无限等待，直到按下任意键
	cv2.destroyWindow("demo")	# 释放销毁指定窗口

In [ ]:
cv2.imshow("demo1", lena)
cv2.imshow("demo2", lena)
key = cv2.waitKey()
if key != -1:
    cv2.destroyAllWindows() # 释放销毁所有窗口
    print("触发了按键！")

触发了按键！


In [9]:
# 保存图像，保存成功，返回值为真，否则为假
r = cv2.imwrite("result.bmp", lena)
print(r)

True


In [10]:
type(lena)

numpy.ndarray

In [ ]:
# 对于类型检查错误，先转换为 UMat 再显示
# cv2.UMat() 全称是 Unified Matrix（统一矩阵）
# 它是 OpenCV 中一种特殊的数据结构, 自动利用 GPU（通过 OpenCL）或 CPU 进行加速
r = cv2.UMat(lena)
type(r)

cv2.UMat

In [12]:
print(r)

< cv2.UMat 0000025FCE5EB670>


#### 1.3 OpenCV 贡献库

- bioinspired：生物视觉模块
- datasets：数据集读取模块
- dnn：深度神经网络模块
- face：人脸识别模块
- matlab：MATLAB接口模块
- stereo：双目立体匹配模块
- text：视觉文本匹配模块
- tracking：基于视觉的目标跟踪模块
- ximgpro：图像处理扩展模块
- xobjdetect：增强2D目标检测模块
- xphoto：计算摄影扩展模块