### 第2章 图像处理基础
#### 2.1 像素处理
- 二值图像和灰度图像

In [ ]:
import cv2
img=cv2.imread("lena.bmp", 0)
cv2.imshow("before", img)
for i in range(10, 100):
    for j in range(70, 100):
        img[i, j]=255   # 设置交叉区域为白色
cv2.imshow("after", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

- RGB 彩色图像

In [ ]:
import numpy as np
import cv2
img=np.zeros((300,300,3), dtype=np.uint8)
img[:, 0:100,0] = 255
img[:, 100:200,1] = 255
img[:, 200:300,2] = 255
print("img=\n", img)
cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

img=
 [[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]]


- 对彩色图像进行访问和修改

In [ ]:
import cv2
img = cv2.imread("lenacolor.png")
cv2.imshow("before", img)
print("访问img[0,0]=", img[0,0])
print("访问img[0,0,0]=", img[0,0,0])
print("访问img[0,0,1]=", img[0,0,1])
print("访问img[0,0,2]=", img[0,0,2])
print("访问img[50,0]=", img[50,0])
print("访问img[100,0]=", img[100,0])
#区域1
for i in range(0, 50):
    for j in range(0, 100):
        for k in range(0, 3):
            img[i, j, k] = 255  # 白色
#区域2
for i in range(50, 100):
    for j in range(0, 100):
        img[i, j] = (128, 128, 128)  # 灰色 元组元素不可变，更适于使用
#区域3            
for i in range(100, 150):
    for j in range(0, 100):
        img[i, j] = 0          # 黑色
cv2.imshow("after", img)
print("修改后img[0,0]=", img[0, 0])
print("修改后img[0,0,0]=", img[0, 0, 0])
print("修改后img[0,0,1]=", img[0, 0, 1])
print("修改后img[0,0,2]=", img[0, 0, 2])
print("修改后img[50,0]=", img[50 ,0])
print("修改后img[100,0]=", img[100, 0])
cv2.waitKey()
cv2.destroyAllWindows()

访问img[0,0]= [125 137 226]
访问img[0,0,0]= 125
访问img[0,0,1]= 137
访问img[0,0,2]= 226
访问img[50,0]= [114 136 230]
访问img[100,0]= [ 75  55 155]
修改后img[0,0]= [255 255 255]
修改后img[0,0,0]= 255
修改后img[0,0,1]= 255
修改后img[0,0,2]= 255
修改后img[50,0]= [128 128 128]
修改后img[100,0]= [0 0 0]


#### 2.2 访问像素
- `item(row, column)`: 更高效地访问图像的像素点

In [1]:
import cv2
img=cv2.imread("lenacolor.png")
cv2.imshow("before", img)
print("访问img.item(0, 0, 0)=", img.item(0, 0, 0))
print("访问img.item(0, 0, 1)=", img.item(0, 0, 1))
print("访问img.item(0, 0, 2)=", img.item(0, 0, 2))
for i in range(0, 50):
    for j in range(0, 100):
        for k in range(0, 3):
            # 在 NumPy 2.0 中，itemset 方法被移除，应替换为 img[i, j, k] = 255
            img[i, j, k] = 255     # 白色
cv2.imshow("after", img)
print("修改后img.item(0,0,0)=", img.item(0, 0, 0))
print("修改后img.item(0,0,1)=", img.item(0, 0, 1))
print("修改后img.item(0,0,2)=", img.item(0, 0, 2))
cv2.waitKey(0)
cv2.destroyAllWindows()

访问img.item(0, 0, 0)= 125
访问img.item(0, 0, 1)= 137
访问img.item(0, 0, 2)= 226
修改后img.item(0,0,0)= 255
修改后img.item(0,0,1)= 255
修改后img.item(0,0,2)= 255


#### 2.3 感兴趣区域 (Region of Interest, ROI)
- 对 lena 图像的脸部进行打码

In [ ]:
import cv2
import numpy as np
a = cv2.imread("lenacolor.png", cv2.IMREAD_UNCHANGED)
cv2.imshow("original", a)
face = np.random.randint(0, 256, (180, 100, 3))
a[220:400,250:350] = face
cv2.imshow("result", a)
cv2.waitKey(0)
cv2.destroyAllWindows()

- 将一幅图像的 ROI 复制到零一幅图像内

In [ ]:
import cv2
lena = cv2.imread("lena512.bmp", cv2.IMREAD_UNCHANGED)
dollar = cv2.imread("dollar.bmp", cv2.IMREAD_UNCHANGED)
cv2.imshow("lena", lena)
cv2.imshow("dollar", dollar)

# 第200行(包含)到第400行(不包含); 第250列(包含)到第350列(不包含)
face = lena[220:400, 250:350] 

dollar[160:340, 200:300] = face
cv2.imshow("result", dollar)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### 2.4 通道操作
- 索引拆分
    - `b = img[:, :, 0]`
    - `g = img[:, :, 1]`
    - `r = img[:, :, 2]`
- 函数拆分
`b, g, r = cv2.split(img)` 等价于
    - `b = cv2.split(img)[0]`
    - `g = cv2.split(img)[1]`
    - `r = cv2.split(img)[2]`

In [5]:
import cv2
lena = cv2.imread("lenacolor.png")
b, g, r = cv2.split(lena)
cv2.imshow("B", b)
cv2.imshow("G", g)
cv2.imshow("R", r)
cv2.waitKey(0)
cv2.destroyAllWindows()

- 通道合并: `cv2.merge()`

In [ ]:
import cv2
lena = cv2.imread("lenacolor.png")
b, g, r  =cv2.split(lena)
bgr = cv2.merge([b, g, r])
rgb = cv2.merge([r, g, b])
cv2.imshow("lena", lena)
cv2.imshow("bgr", bgr)  # OpenCV 中通道顺序是 BGR
cv2.imshow("rgb", rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()

- 获取图像属性

In [7]:
import cv2
gray = cv2.imread("lena.bmp",0)
color = cv2.imread("lenacolor.png")
print("图像gray属性：")
print("gray.shape=", gray.shape)
print("gray.size=", gray.size)
print("gray.dtype=", gray.dtype)
print("图像color属性：")
print("color.shape=", color.shape)
print("color.size=", color.size)
print("color.dtype=", color.dtype)

图像gray属性：
gray.shape= (256, 256)
gray.size= 65536
gray.dtype= uint8
图像color属性：
color.shape= (512, 512, 3)
color.size= 786432
color.dtype= uint8
